config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :tasks
  resources :users
  resources :references
  resources :risks
  resources :projects

   root 'static_pages#home'
   get 'help' => 'static_pages#help'
   get 'projects' => 'static_pages#projects'
   get 'contact' => 'static_pages#contact'
   get 'about' => 'static_pages#about'
   get 'signup' => 'users#new'
   get 'login' => 'sessions#new'
   post 'login' => 'sessions#create'
   delete 'logout' => 'sessions#destroy'
   
   resources :users 

end

app/models/reference.rb
class Reference < ActiveRecord::Base
    belongs_to :project
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update, :destroy]

  # GET /references
  # GET /references.json
  def index
    @references = Reference.all
  end

  # GET /references/1
  # GET /references/1.json
  def show
  end

  # GET /references/new
  def new
    @reference = Reference.new
  end

  # GET /references/1/edit
  def edit
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(reference_params)

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to references_url, notice: 'Reference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:ref_title, :ref_desc, :ref_link, :ref_type)
    end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.erb
<%= form_for(@reference) do |f| %>
  <% if @reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% @reference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ref_title %><br>
    <%= f.text_field :ref_title %>
  </div>
  <div class="field">
    <%= f.label :ref_desc %><br>
    <%= f.text_area :ref_desc %>
  </div>
  <div class="field">
    <%= f.label :ref_link %><br>
    <%= f.text_field :ref_link %>
  </div>
  <div class="field">
    <%= f.label :ref_type %><br>
    <%= f.text_field :ref_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/references/edit.html.erb
<h1>Editing Reference</h1>

<%= render 'form' %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', references_path %>

app/views/references/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing References</h1>

<table>
  <thead>
    <tr>
      <th>Ref title</th>
      <th>Ref desc</th>
      <th>Ref link</th>
      <th>Ref type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @references.each do |reference| %>
      <tr>
        <td><%= reference.ref_title %></td>
        <td><%= reference.ref_desc %></td>
        <td><%= reference.ref_link %></td>
        <td><%= reference.ref_type %></td>
        <td><%= link_to 'Show', reference %></td>
        <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference', new_reference_path %>

app/views/references/new.html.erb
<h1>New Reference</h1>

<%= render 'form' %>

<%= link_to 'Back', references_path %>

app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ref title:</strong>
  <%= @reference.ref_title %>
</p>

<p>
  <strong>Ref desc:</strong>
  <%= @reference.ref_desc %>
</p>

<p>
  <strong>Ref link:</strong>
  <%= @reference.ref_link %>
</p>

<p>
  <strong>Ref type:</strong>
  <%= @reference.ref_type %>
</p>

<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', references_path %>